### ISSUE TITLE
Dependency Hell -> Could not resolve androidx.core:core:1.0.1.

### ISSUE THREAD

**Issue by Macilias** [ppsreejith/react-native-camera-tflite#6]
# Bug Report
**To Do First**
- [x] Did you try latest release?
- [X] Did you try master?
- [X] Did you look for existing matching issues?

**Related Modules**
androidx.legacy:legacy-support

**Platforms**

Android

**Versions**

- Android:
- iOS:
- react-native-camera:
- react-native:
- react:

**Description/Current Behaviour**

I just followed the instructions and created a new project which turned out to be 
"dependencies": {
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-camera-tflite": "0.0.3",
    "lodash": "latest"
  },

when I run android I end up in this dependency hell:
```
* What went wrong:
Could not determine the dependencies of task ':react-native-camera-tflite:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':react-native-camera-tflite:debugCompileClasspath'.
   > Could not resolve androidx.core:core:{strictly 1.0.0}.
     Required by:
         project :react-native-camera-tflite
      > Cannot find a version of 'androidx.core:core' that satisfies the version constraints: 
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.core:core:1.0.0'
           Constraint path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'androidx.core:core:{strictly 1.0.0}' because of the following reason: debugRuntimeClasspath uses version 1.0.0
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'com.facebook.react:react-native:0.61.5' --> 'androidx.appcompat:appcompat:1.0.2' --> 'androidx.core:core:1.0.1'
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.media:media:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.legacy:legacy-support-core-utils:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'com.facebook.react:react-native:0.61.5' --> 'androidx.appcompat:appcompat:1.0.2' --> 'androidx.vectordrawable:vectordrawable:1.0.1' --> 'androidx.core:core:1.0.0'
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.legacy:legacy-support-core-utils:1.0.0' --> 'androidx.loader:loader:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.customview:customview:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.viewpager:viewpager:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.coordinatorlayout:coordinatorlayout:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.drawerlayout:drawerlayout:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.slidingpanelayout:slidingpanelayout:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.swiperefreshlayout:swiperefreshlayout:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.asynclayoutinflater:asynclayoutinflater:1.0.0' --> 'androidx.core:core:1.0.0'

   > Could not resolve androidx.core:core:1.0.0.
     Required by:
         project :react-native-camera-tflite > androidx.legacy:legacy-support-v4:1.0.0
         project :react-native-camera-tflite > androidx.media:media:1.0.0
         project :react-native-camera-tflite > androidx.legacy:legacy-support-core-utils:1.0.0
         project :react-native-camera-tflite > androidx.legacy:legacy-support-core-ui:1.0.0
         project :react-native-camera-tflite > androidx.fragment:fragment:1.0.0
         project :react-native-camera-tflite > com.facebook.react:react-native:0.61.5 > androidx.appcompat:appcompat:1.0.2 > androidx.vectordrawable:vectordrawable:1.0.1
         project :react-native-camera-tflite > androidx.loader:loader:1.0.0
         project :react-native-camera-tflite > androidx.customview:customview:1.0.0
         project :react-native-camera-tflite > androidx.viewpager:viewpager:1.0.0
         project :react-native-camera-tflite > androidx.coordinatorlayout:coordinatorlayout:1.0.0
         project :react-native-camera-tflite > androidx.drawerlayout:drawerlayout:1.0.0
         project :react-native-camera-tflite > androidx.slidingpanelayout:slidingpanelayout:1.0.0
         project :react-native-camera-tflite > androidx.swiperefreshlayout:swiperefreshlayout:1.0.0
         project :react-native-camera-tflite > androidx.asynclayoutinflater:asynclayoutinflater:1.0.0
      > Cannot find a version of 'androidx.core:core' that satisfies the version constraints: 
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.core:core:1.0.0'
           Constraint path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'androidx.core:core:{strictly 1.0.0}' because of the following reason: debugRuntimeClasspath uses version 1.0.0
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'com.facebook.react:react-native:0.61.5' --> 'androidx.appcompat:appcompat:1.0.2' --> 'androidx.core:core:1.0.1'
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.media:media:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.legacy:legacy-support-core-utils:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'com.facebook.react:react-native:0.61.5' --> 'androidx.appcompat:appcompat:1.0.2' --> 'androidx.vectordrawable:vectordrawable:1.0.1' --> 'androidx.core:core:1.0.0'
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.legacy:legacy-support-core-utils:1.0.0' --> 'androidx.loader:loader:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.customview:customview:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.viewpager:viewpager:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.coordinatorlayout:coordinatorlayout:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.drawerlayout:drawerlayout:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.slidingpanelayout:slidingpanelayout:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.swiperefreshlayout:swiperefreshlayout:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.asynclayoutinflater:asynclayoutinflater:1.0.0' --> 'androidx.core:core:1.0.0'

   > Could not resolve androidx.core:core:1.0.1.
     Required by:
         project :react-native-camera-tflite > com.facebook.react:react-native:0.61.5 > androidx.appcompat:appcompat:1.0.2
      > Cannot find a version of 'androidx.core:core' that satisfies the version constraints: 
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.core:core:1.0.0'
           Constraint path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'androidx.core:core:{strictly 1.0.0}' because of the following reason: debugRuntimeClasspath uses version 1.0.0
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'com.facebook.react:react-native:0.61.5' --> 'androidx.appcompat:appcompat:1.0.2' --> 'androidx.core:core:1.0.1'
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.media:media:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.legacy:legacy-support-core-utils:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'com.facebook.react:react-native:0.61.5' --> 'androidx.appcompat:appcompat:1.0.2' --> 'androidx.vectordrawable:vectordrawable:1.0.1' --> 'androidx.core:core:1.0.0'
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.legacy:legacy-support-core-utils:1.0.0' --> 'androidx.loader:loader:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.customview:customview:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.viewpager:viewpager:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.coordinatorlayout:coordinatorlayout:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.drawerlayout:drawerlayout:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.slidingpanelayout:slidingpanelayout:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.swiperefreshlayout:swiperefreshlayout:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'mobilenetapp:react-native-camera-tflite:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.asynclayoutinflater:asynclayoutinflater:1.0.0' --> 'androidx.core:core:1.0.0'


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s

    at checkExecSyncError (child_process.js:621:11)
    at execFileSync (child_process.js:639:15)
    at runOnAllDevices (/home/maciek/mac/playground/mobilenetapp/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:39)
    at buildAndRun (/home/maciek/mac/playground/mobilenetapp/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:158:41)
    at /home/maciek/mac/playground/mobilenetapp/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:125:12

```

**Expected Behaviour**
The application should start 

**Steps to Reproduce**
Just follow the README.md instructions

**Additionals**

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by Papaass** [comment]
Hello Macilias ,
Have you solved the issue ?
If yes how ?

**Comment by Macilias** [comment]
Apparently I didn’t, I guess I would need to use an old react version or fork this repo and update the dependencies my self, but it’s too much hassle - we want to use plain tensorflow modules anyway.

**Comment by Papaass** [comment]
Yes, that's right, you need an earlier version of react. 
One question: did you manage to deploy a tensorflow tflite model in a streaming video in react?

**Comment by Macilias** [comment]
Actually its still on my TODO list. I had to finish some other tasks before Christmas and left this one for the new year. We can stay in touch and get it up and running together next week if you like.

**Comment by Papaass** [comment]
it's okay for me. It would just be good for both of us.

**Comment by Macilias** [comment]
cool, I´ll start working on it next week, have a nice Sylvester party :)

**Comment by Papaass** [comment]
Hello @Macilias 
What the news ?

**Comment by Macilias** [comment]
I'm working currently on the redux side of the app, but once its done I'll finally return the camera

**Comment by Papaass** [comment]
Can you share with me after you're finished doing that ?

**Comment by Macilias** [comment]
Sure

El Hadji Abdoulaye THIAM <notifications@github.com> schrieb am Mo. 6. Jan.
2020 um 15:23:

**Comment by Macilias** [comment]
Hi Papaass I gave it a shot and tried to rebase the project to the current react-native-camera state, so It could fit into current react environment. However there should still more work be applied to to bring it back to life, since there has been lot of braking changes, for example they have moved to firebase ML services which also include Tensorflow, so some things should be (re)implemented to cover the changes. Anyway I need to stop working on this, since we would like to support TF and TFLite and only TFLite is covered by this particular approach.
Anyway, you can find the current state of affairs here: https://github.com/Macilias/react-native-camera-tflite-updated/commits/master
